name: module3_task0
on:
  push:
  schedule:
    - cron: '0 0 * * *'
jobs:
  # single job
  build:
    runs-on: ubuntu-latest
    #single step representing the task
    steps:
      - uses: actions/checkout@v3
      - run: cd module3_task0 && make help
